{
 "title": "k8s-kafka",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "label-2",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "label-1",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Jobs",
   "type": "graph",
   "description": "UP/DOWN",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{namespace=\"default\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Received Messages",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Byets In/Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps", "label": "- bytes out / + bytes in" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"\"}[1m])",
     "legendFormat": "{{pod}} (bytes in)"
    },
    {
     "expr": "-rate(kafka_server_brokertopicmetrics_bytesout_total{topic=\"\"}[1m])",
     "legendFormat": "{{pod}} (bytes out)"
    }
   ]
  },
  { "title": "System", "type": "text", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 31 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Iowait"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Total"
    }
   ]
  },
  {
   "title": "CPU Usage by processess",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "{{instance}}: {{job}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_15m"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_Avaliable"
    }
   ]
  },
  {
   "title": "GC Collection time ms per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum[1m])*1000",
     "legendFormat": "({{instance}}) {{gc}}"
    }
   ]
  },
  {
   "title": "Classes loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_classes_loaded", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "current  {{instance}}" },
    { "expr": "jvm_threads_deadlocked", "legendFormat": "deadlocked {{instance}}" },
    { "expr": "jvm_threads_peak", "legendFormat": "peak {{instance}}" }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{instance}}_{{device}}_receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{instance}}_{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "graph",
   "description": "TCP_alloc - Allocated sockets\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nSockets_used - Sockets currently in use",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "{{instance}}_CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
     "legendFormat": "{{instance}}_TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~'$node'}",
     "legendFormat": "{{instance}}_Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~'$node'}",
     "legendFormat": "{{instance}}_UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "{{instance}}_TCP_alloc"
    }
   ]
  },
  {
   "title": "Open  File Descriptor(left)/Context switches(right)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}",
     "legendFormat": "filefd_{{instance}}"
    },
    {
     "expr": "irate(node_context_switches_total{instance=~\"$node\"}[30m])",
     "legendFormat": "switches_{{instance}}"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "graph",
   "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_ IO time"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic(EXT4/XFS)",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 142 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 148 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{instance}}：{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 161 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Disk R/W Time(Reference: less than 100ms)(beta)",
   "type": "graph",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 174 },
   "yaxes": [
    { "format": "s", "label": "Time. read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[30m]) / irate(node_disk_reads_completed_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Read time"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[30m]) / irate(node_disk_writes_completed_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Write time"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "graph",
   "description": "Read/write completions per second",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 186 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Writes completed"
    }
   ]
  }
 ]
}